<?php

namespace WCS\CoavBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * PlaneModel
 *
 * @ORM\Table(name="plane_model")
 * @ORM\Entity(repositoryClass="WCS\CoavBundle\Repository\PlaneModelRepository")
 */
class PlaneModel
{

    /*Adding personnal methods */
    public function __toString()
    {
            //Return the plane object with "[model] format when __toString is called.
            return $this->model;
    }

/*CLI and autogenerated methods*/

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
    * @var string
     *
     * @ORM\Column(name="model", type="string", length=64)
    * @ORM\OneToMany(targetEntity="WCS\CoavBundle\Entity\Flight")
    */
    private $model;

    /**
     * @var string
     *
     * @ORM\Column(name="manufacturer", type="string", length=64)
     */
    private $manufacturer;

    /**
     * @var int
     *
     * @ORM\Column(name="cruiseSpeed", type="smallint", nullable=true)
     */
    private $cruiseSpeed;

    /**
     * @var int
     *
     * @ORM\Column(name="planeNbSeats", type="smallint")
     */
    private $planeNbSeats;

    /**
     * @var bool
     *
     * @ORM\Column(name="isAvailable", type="boolean")
     */
    private $isAvailable;


    /**
    * @ORM\OneToMany(targetEntity="WCS\CoavBundle\Entity\Flight")
    */
    private $plane;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set model
     *
     * @param string $model
     *
     * @return PlaneModel
     */
    public function setModel($model)
    {
        $this->model = $model;

        return $this;
    }

    /**
     * Get model
     *
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Set manufacturer
     *
     * @param string $manufacturer
     *
     * @return PlaneModel
     */
    public function setManufacturer($manufacturer)
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }

    /**
     * Get manufacturer
     *
     * @return string
     */
    public function getManufacturer()
    {
        return $this->manufacturer;
    }

    /**
     * Set cruiseSpeed
     *
     * @param integer $cruiseSpeed
     *
     * @return PlaneModel
     */
    public function setCruiseSpeed($cruiseSpeed)
    {
        $this->cruiseSpeed = $cruiseSpeed;

        return $this;
    }

    /**
     * Get cruiseSpeed
     *
     * @return int
     */
    public function getCruiseSpeed()
    {
        return $this->cruiseSpeed;
    }

    /**
     * Set planeNbSeats
     *
     * @param integer $planeNbSeats
     *
     * @return PlaneModel
     */
    public function setPlaneNbSeats($planeNbSeats)
    {
        $this->planeNbSeats = $planeNbSeats;

        return $this;
    }

    /**
     * Get planeNbSeats
     *
     * @return int
     */
    public function getPlaneNbSeats()
    {
        return $this->planeNbSeats;
    }

    /**
     * Set isAvailable
     *
     * @param boolean $isAvailable
     *
     * @return PlaneModel
     */
    public function setIsAvailable($isAvailable)
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    /**
     * Get isAvailable
     *
     * @return bool
     */
    public function getIsAvailable()
    {
        return $this->isAvailable;
    }

    /**
     * Set plane
     *
     * @param \WCS\CoavBundle\Entity\Flight $plane
     *
     * @return PlaneModel
     */
    public function setPlane(\WCS\CoavBundle\Entity\Flight $plane)
    {
        $this->plane = $plane;

        return $this;
    }

    /**
     * Get plane
     *
     * @return \WCS\CoavBundle\Entity\Flight
     */
    public function getPlane()
    {
        return $this->plane;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->model = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add model
     *
     * @param \WCS\CoavBundle\Entity\Flight $model
     *
     * @return PlaneModel
     */
    public function addModel(\WCS\CoavBundle\Entity\Flight $model)
    {
        $this->model[] = $model;

        return $this;
    }

    /**
     * Remove model
     *
     * @param \WCS\CoavBundle\Entity\Flight $model
     */
    public function removeModel(\WCS\CoavBundle\Entity\Flight $model)
    {
        $this->model->removeElement($model);
    }

    /**
     * Add plane
     *
     * @param \WCS\CoavBundle\Entity\Flight $plane
     *
     * @return PlaneModel
     */
    public function addPlane(\WCS\CoavBundle\Entity\Flight $plane)
    {
        $this->plane[] = $plane;

        return $this;
    }

    /**
     * Remove plane
     *
     * @param \WCS\CoavBundle\Entity\Flight $plane
     */
    public function removePlane(\WCS\CoavBundle\Entity\Flight $plane)
    {
        $this->plane->removeElement($plane);
    }
}
